### ISSUE TITLE
Add the checking with classes, not with id

### ISSUE THREAD

**Issue by Arrogance** [orta-sanz/adblock-detecter#2]
Hi pal!

I think is better to check via classes, not id. You can add several class names (Ex: 'adsbox ad ads publicidad publi'). I can push a merge with theses changes.

**Comment by orta-sanz** [comment]
Great stuff mate! :) Feel free to push any improvements you want, I'm with you, better to check using classes

**Comment by orta-sanz** [comment]
Already updated, now we are using class names instead of id
